//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThingsToDo
    {
        public int id { get; set; }
        public string thingToDo { get; set; }
        public Nullable<int> dateID { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        public string mainImage { get; set; }
    
        public virtual Date Date { get; set; }
    }
}
